// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";
import { Timestamp } from "../../google/protobuf/Timestamp";

export class Usdc_CancelAuthorization1call {
  static encode(message: Usdc_CancelAuthorization1call, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.callTxHash);

    const callBlockTime = message.callBlockTime;
    if (callBlockTime !== null) {
      writer.uint32(18);
      writer.fork();
      Timestamp.encode(callBlockTime, writer);
      writer.ldelim();
    }

    writer.uint32(24);
    writer.uint64(message.callBlockNumber);

    writer.uint32(32);
    writer.uint64(message.callOrdinal);

    writer.uint32(40);
    writer.bool(message.callSuccess);

    writer.uint32(50);
    writer.bytes(message.authorizer);

    writer.uint32(58);
    writer.bytes(message.nonce);

    writer.uint32(64);
    writer.uint64(message.v);

    writer.uint32(74);
    writer.bytes(message.r);

    writer.uint32(82);
    writer.bytes(message.s);
  }

  static decode(reader: Reader, length: i32): Usdc_CancelAuthorization1call {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Usdc_CancelAuthorization1call();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.callTxHash = reader.string();
          break;

        case 2:
          message.callBlockTime = Timestamp.decode(reader, reader.uint32());
          break;

        case 3:
          message.callBlockNumber = reader.uint64();
          break;

        case 4:
          message.callOrdinal = reader.uint64();
          break;

        case 5:
          message.callSuccess = reader.bool();
          break;

        case 6:
          message.authorizer = reader.bytes();
          break;

        case 7:
          message.nonce = reader.bytes();
          break;

        case 8:
          message.v = reader.uint64();
          break;

        case 9:
          message.r = reader.bytes();
          break;

        case 10:
          message.s = reader.bytes();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  callTxHash: string;
  callBlockTime: Timestamp | null;
  callBlockNumber: u64;
  callOrdinal: u64;
  callSuccess: bool;
  authorizer: Uint8Array;
  nonce: Uint8Array;
  v: u64;
  r: Uint8Array;
  s: Uint8Array;

  constructor(
    callTxHash: string = "",
    callBlockTime: Timestamp | null = null,
    callBlockNumber: u64 = 0,
    callOrdinal: u64 = 0,
    callSuccess: bool = false,
    authorizer: Uint8Array = new Uint8Array(0),
    nonce: Uint8Array = new Uint8Array(0),
    v: u64 = 0,
    r: Uint8Array = new Uint8Array(0),
    s: Uint8Array = new Uint8Array(0)
  ) {
    this.callTxHash = callTxHash;
    this.callBlockTime = callBlockTime;
    this.callBlockNumber = callBlockNumber;
    this.callOrdinal = callOrdinal;
    this.callSuccess = callSuccess;
    this.authorizer = authorizer;
    this.nonce = nonce;
    this.v = v;
    this.r = r;
    this.s = s;
  }
}
